# Generated by Django 4.2.5 on 2023-10-14 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BuyPortfolio",
            fields=[
                ("business_date", models.DateField(default=datetime.datetime.today)),
                ("settlement_date", models.DateField(default=datetime.datetime.today)),
                ("symbol", models.CharField(default="API", max_length=10)),
                ("buy_rate", models.FloatField(default=0.0)),
                ("quantity", models.IntegerField(default=0)),
                ("buy_amount", models.FloatField(default=0.0)),
                ("broker_commission", models.FloatField(default=0.0)),
                ("sebon_commission", models.FloatField(default=0.0)),
                ("dp_charge", models.FloatField(default=0.0)),
                ("total_commission", models.FloatField(default=0.0)),
                ("paid_amount", models.FloatField(default=0.0)),
                ("effective_rate", models.FloatField(default=0.0)),
                (
                    "payment_status",
                    models.CharField(default="NET_SETTLEMENT_SUCCESS", max_length=30),
                ),
                (
                    "settlement_status",
                    models.CharField(default="SETTLED", max_length=30),
                ),
                (
                    "transaction_number",
                    models.BigIntegerField(
                        default=0, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveIndex",
            fields=[
                (
                    "indexCode",
                    models.CharField(
                        default="NEPSE",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("indexValue", models.FloatField(default=0.0)),
                ("prevCloseIndex", models.FloatField(default=0.0)),
                ("change", models.FloatField(default=0.0)),
                ("percentageChange", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="LiveTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ltp", models.FloatField(default=0.0)),
                ("percentChange", models.FloatField(default=0.0)),
                ("change", models.FloatField(default=0.0)),
                ("open", models.FloatField(default=0)),
                ("high", models.FloatField(default=0)),
                ("low", models.FloatField(default=0)),
                ("volume", models.BigIntegerField(default=0)),
                ("lastTradedVolume", models.IntegerField(default=0)),
                ("lastTradedTime", models.CharField(default="", max_length=30)),
                ("previousClose", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="SellPortfolio",
            fields=[
                ("business_date", models.DateField(default=datetime.datetime.today)),
                ("settlement_date", models.DateField(default=datetime.datetime.today)),
                ("symbol", models.CharField(default="API", max_length=10)),
                ("sell_rate", models.FloatField(default=0.0)),
                ("quantity", models.IntegerField(default=0)),
                ("sell_amount", models.FloatField(default=0.0)),
                ("broker_commission", models.FloatField(default=0.0)),
                ("sebon_commission", models.FloatField(default=0.0)),
                ("dp_charge", models.FloatField(default=0.0)),
                ("total_commission", models.FloatField(default=0.0)),
                ("cgt_charge", models.FloatField(default=0.0)),
                ("received_amount", models.FloatField(default=0.0)),
                ("effective_rate", models.FloatField(default=0.0)),
                (
                    "payment_status",
                    models.CharField(default="NET_SETTLEMENT_SUCCESS", max_length=30),
                ),
                (
                    "settlement_status",
                    models.CharField(default="SETTLED", max_length=30),
                ),
                (
                    "transaction_number",
                    models.BigIntegerField(
                        default=0, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SummaryPortfolio",
            fields=[
                ("date", models.DateField(default=datetime.datetime.today)),
                ("type", models.CharField(default="BUY", max_length=10)),
                ("symbol", models.CharField(default="API", max_length=10)),
                ("rate", models.FloatField(default=0.0)),
                ("quantity", models.IntegerField(default=0)),
                ("amount", models.FloatField(default=0.0)),
                ("pl_status", models.CharField(default="Profit", max_length=10)),
                ("pl_percent", models.FloatField(default=0.0)),
                ("pl_amount", models.FloatField(default=0.0)),
                ("holding_days", models.IntegerField(default=0)),
                (
                    "transaction_number",
                    models.BigIntegerField(
                        default=0, primary_key=True, serialize=False
                    ),
                ),
            ],
        ),
    ]
