# Generated by Django 4.2.5 on 2023-10-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("khiladi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="livetable",
            name="symbol",
            field=models.CharField(default="API", max_length=10),
        ),
    ]
